# Generated by Django 4.0 on 2023-09-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driverApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='driver',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
