# Generated by Django 4.0 on 2023-09-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverApp', '0002_remove_booking_driver_delete_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email_driver',
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('Utilisateur', 'Utilisateur'), ('Chauffeur', 'Chauffeur')], max_length=100),
        ),
    ]
